#! /bin/bash


_ArankBot_zip () {
    if [[ $PLUGINS_REPO ]]
    then
        echo "https://github.com/${PLUGINS_REPO}/archive/master.zip"
    else
        echo "https://github.com/CoderXHitler/Plugins/archive/master.zip"
    fi
}

_starter () {
    echo "••• Downloading ArankBot [v3] •••"
    hellpath="Plugins.zip"

    wget -q $(_ArankBot_zip) -O "$hellpath"
    HELLPATH=$(zipinfo -1 "$hellpath" | grep -v "/.");
    unzip -qq "$aranklpath"
    rm -rf "$hellpath"
    cd $HELLPATH
    python3 ../updater.py ../requirements.txt requirements.txt

    echo "••• Starting ArankBot [v3] •••"
    chmod 777 start.sh
    ./start.sh
}

_starter
