#! /bin/bash


_ArankBot_zip () {
    if [[ $PLUGINS_REPO ]]
    then
        echo "https://github.com/${PLUGINS_REPO}/archive/master.zip"
    else
        echo "https://github.com/CoderXHitler/Plugins/archive/master.zip"
    fi
}

_starter () {
    echo "••• Downloading ArankBot [v3] •••"
    arankpath="Plugins.zip"

    wget -q $(_ArankBot_zip) -O "$arankpath"
    ARANKPATH=$(zipinfo -1 "$arankpath" | grep -v "/.");
    unzip -qq "$arankpath"
    rm -rf "$arankpath"
    cd $arankPATH
    python3 ../updater.py ../requirements.txt requirements.txt

    echo "••• Starting ArankBot [v3] •••"
    chmod 777 start.sh
    ./start.sh
}

_starter
